### ISSUE TITLE
AWK fails to compile regex

### ISSUE THREAD

**Issue by light2802** [AdeshChoudhar/SE_I_Lab_ASC#1]
This is not compliant with requirement

You're probably using  GNU awk which has many more features than mawk which comes default with ubuntu. So your program may not run successfully on all machines.

AWK does have various implementations, project you attempt to run require GNU AWK (also known as gawk) whilst you provide it Michael Brennan's implementation (mawk).

**Comment by AdeshChoudhar** [comment]
@light2802 assigned to you.

**Comment by light2802** [comment]
resolved for ubuntu for now
